
version: "3"

services:
  signer:
    hostname: signer
    image: enigmampc/eth-bridge:0.8.0
    volumes:
      - /replace/this/with/keys/path/:/root/keys  # map the path where the file specified by "secret_key_name" exists
    environment:
      # general
      - SWAP_ENV=TESTNET

      # database config
      - db_username=memyselfandI
      - db_password=supersecret
      - db_host=url_to_db.com

      # access nodes
      - eth_node="https://ropsten.infura.io/v3/..."
      - secret_node="tcp://bootstrap.secrettestnet.io:26657"
      
      # scrt keys config
      - secret_key_name=t1
      - secret_key_file=t1.key
      - secret_key_password=12345678

      # eth key option 1 - hardcoded private key
      - eth_private_key=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa   # ethereum private key
      - eth_address=0xbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb                     # ethereum account address

      # provided by leader
      - multisig_acc_addr=secret1v9gjeejjzrp80wysulevc9dgq2fn80ahfyrvsy
      - multisig_wallet_address=0x3375630Eff4AAcBF59195470F60aabC218e808D6
      - secret_signers=secretpub1addwnpepqwamxgvaeayyhlsh5htwx9z8vh40vnm5fwlr5axzn6jheeyv3yxhv2qk5p7,secretpub1addwnpepqf080zg7qhwh7wx777jfnyaemp366778edfc5yt7238m3vk03a75ypdtyzk,secretpub1addwnpepqfr4h7p7ylhyjuv0fcef22wu28sgdqljhnz9dtrpafhs4hdkn4r9z3w2z2n
      - scrt_swap_address=secret1qdazdmdq65cgrpgmkcqen2u8yg3e9h6eh9ld99
      - swap_code_hash=9263D9A2026FECC5A99534E84706230AAC6590AA342434A84B7F8A43DFAAF9E3

      # eth key option 2 - pkcs11 module (only softhsm supported currently)
      # volumes: (you may want to map the token storage path to a path inside the container)
      #   - /path/to/tokens:/root/hsm/tokens/
      # environment:
      #   - token=token
      #   - user_pin=1234
      #   - label=label
